# Generated by Django 4.2 on 2023-05-13 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BankManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAccount',
            fields=[
                ('CAccount_ID', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='CAccount_ID')),
                ('CAccount_Balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='CAccount_Balance')),
                ('CAccount_Open_Date', models.DateTimeField(verbose_name='CAccount_Open_Date')),
            ],
            options={
                'db_table': 'CheckAccount',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='Customer_ID')),
                ('Customer_Name', models.CharField(max_length=255, verbose_name='Customer_Name')),
                ('Customer_Phone_Number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Customer_Phone_Number')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='Employee_ID')),
                ('Employee_Name', models.CharField(max_length=255, verbose_name='Employee_Name')),
                ('Employee_Hire_Date', models.DateTimeField(verbose_name='Employee_Hire_Date')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('SAccount_ID', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='SAccount_ID')),
                ('SAccount_Balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='SAccount_Balance')),
                ('SAccount_Open_Date', models.DateTimeField(verbose_name='SAccount_Open_Date')),
            ],
            options={
                'db_table': 'SavingAccount',
            },
        ),
        migrations.CreateModel(
            name='CustomerToSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAccount_Last_Access_Date', models.DateTimeField(auto_now=True, verbose_name='SAccount_Last_Access_Date')),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankManagement.customer')),
                ('SAccount_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankManagement.savingaccount')),
            ],
            options={
                'db_table': 'CustomerToSA',
            },
        ),
        migrations.CreateModel(
            name='CustomerToCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAccount_Last_Access_Date', models.DateTimeField(auto_now=True, verbose_name='CAccount_Last_Access_Date')),
                ('CAccount_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankManagement.checkaccount')),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankManagement.customer')),
            ],
            options={
                'db_table': 'CustomerToCA',
            },
        ),
    ]
